steps:
  - name: maven:latest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true", "--cache-from", ".m2/repository"]
  - name: node:latest
    dir: nodejs
    entrypoint: npm
    args: ["install", "--cache-from", "node_modules/"]
    waitFor: ['-']
  - name: node:latest
    dir: nodejs
    entrypoint: npm
    args: ["build", "--cache-from", "node_modules/"]
    waitFor: ['-']
  - name: maven:latest
    entrypoint: mvn
    args: ["test"]
  - name: node:latest
    dir: nodejs/src
    entrypoint: npm
    args: ["run test"]
