steps:
  - name: maven:latest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: node:latest
    dir: nodejs
    entrypoint: npm
    args: ["install"]
  - name: node:latest
    dir: nodejs
    entrypoint: npm
    args: ["run", "build"]
  - name: maven:latest
    entrypoint: mvn
    args: ["test"]
  - name: node:latest
    dir: nodejs/src
    entrypoint: npm
    args: ["run test"]
