steps:
  - name: maven:latest
    entrypoint: mvn
    args: ["test"]
  - name: nod:latest
    entrypoint: npm
    args: ["test"]
  - name: maven:latest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
