steps:
  - name: maven:latest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: node:latest
    dir: nodejs
    entrypoint: npm
    args: ["install", "--cache-from", "src/"]
    waitFor: ['-']
  - name: node:latest
    dir: nodejs
    entrypoint: npm
    args: ["build"]
    waitFor: ['-']
  - name: maven:latest
    entrypoint: mvn
    args: ["test"]
  - name: node:latest
    dir: nodejs/src
    entrypoint: npm
    args: ["run test"]
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/my first project/myimage', '.']
